import sys

if sys.platform == 'linux':
    WINE = 'wine'
    FILE_PATH_SEPARATOR = '/'
    pass
else:
    WINE = ''  # Windows doesn't need wine
    FILE_PATH_SEPARATOR = '\\'
    pass

PRETTY_LANGUAGE_DEFAULT = 'jpn'
PRETTY_LANGUAGE_CURRENT = 'eng'
PRETTY_PATH = f'..{FILE_PATH_SEPARATOR}pretty'
PRETTY_PATH_DEFAULT = f'{PRETTY_PATH}_{PRETTY_LANGUAGE_DEFAULT}'
PRETTY_PATH_CURRENT = f'{PRETTY_PATH}_{PRETTY_LANGUAGE_CURRENT}'

PATH_SCN = f'..{FILE_PATH_SEPARATOR}SCN'
PATH_SCN_ORIGINAL =  f'{PATH_SCN}{FILE_PATH_SEPARATOR}ORIGINAL'
PATH_SCN_WORKING = f'{PATH_SCN}{FILE_PATH_SEPARATOR}MODIFIED'
